features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://Drupal-EDU-original.png'
favicon:
  use_default: false
  path: 'public://favicon-96x96.png'
  mimetype: image/png
